// ============================================================
// DarkFlix - Dados Iniciais de Filmes e Séries
// ============================================================

const DEFAULT_MOVIES = [
  {
    id: 1,
    title: "Interestelar",
    year: 2014,
    duration: "2h 49m",
    rating: 8.7,
    type: "movie",
    featured: true,
    videoType: "url",
    genres: ["Ficção Científica", "Drama", "Aventura"],
    description: "As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, garantindo a sobrevivência da espécie humana.",
    poster: "https://image.tmdb.org/t/p/w500/nCbkOyOMTEwlEV0LtCObySSRFhk.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg",
    video: "https://www.youtube.com/embed/zSWdZVtXT7E?autoplay=1"
  },
  {
    id: 2,
    title: "O Poderoso Chefão",
    year: 1972,
    duration: "2h 55m",
    rating: 9.2,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Crime", "Drama"],
    description: "Uma família de Nova York, durante os anos 40, é chefiada por Don Vito Corleone. Ele é o chefão da máfia e comanda com mão de ferro os negócios ilícitos, se tornando o homem mais poderoso da cidade.",
    poster: "https://image.tmdb.org/t/p/w500/oJagOzBu9Rdd9BrciseCm3U3MCU.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    video: "https://www.youtube.com/embed/UaVTIH8mujA?autoplay=1"
  },
  {
    id: 3,
    title: "Batman: O Cavaleiro das Trevas",
    year: 2008,
    duration: "2h 32m",
    rating: 9.0,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ação", "Crime", "Drama"],
    description: "Com a ajuda do tenente Jim Gordon e do promotor público Harvey Dent, Batman enfrenta o Coringa, um gênio do crime que semeia o caos e a destruição em Gotham City.",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BytUESw3KFkt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg",
    video: "https://www.youtube.com/embed/EXeTwQWrcwY?autoplay=1"
  },
  {
    id: 4,
    title: "Clube da Luta",
    year: 1999,
    duration: "2h 19m",
    rating: 8.8,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Drama", "Thriller"],
    description: "Um homem deprimido que sofre de insônia conhece Tyler Durden, um vendedor de sabão despreocupado. Juntos, eles formam um clube do luta clandestino que evolui para algo muito mais perigoso.",
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/hZkgoQYus5dXo3H8T7CYV2UImTl.jpg",
    video: "https://www.youtube.com/embed/qtRKdVHc-cE?autoplay=1"
  },
  {
    id: 5,
    title: "Inception: A Origem",
    year: 2010,
    duration: "2h 28m",
    rating: 8.8,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Ação", "Thriller"],
    description: "Dom Cobb é um ladrão habilidoso que rouba segredos corporativos usando tecnologia de compartilhamento de sonhos. Ele recebe a chance de ter sua vida de volta se conseguir realizar o inverso: implantar uma ideia na mente de alguém.",
    poster: "https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    video: "https://www.youtube.com/embed/YoHD9XEInc0?autoplay=1"
  },
  {
    id: 6,
    title: "Matrix",
    year: 1999,
    duration: "2h 16m",
    rating: 8.7,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Ação"],
    description: "O hacker Neo descobre que o mundo em que vive é uma realidade simulada criada por máquinas. Guiado por Morpheus, ele embarca em uma jornada para libertar a humanidade.",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
    video: "https://www.youtube.com/embed/vKQi3bBA1y8?autoplay=1"
  },
  {
    id: 7,
    title: "Parasita",
    year: 2019,
    duration: "2h 12m",
    rating: 8.5,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Thriller", "Comédia", "Drama"],
    description: "A família Kim, que vive em um porão apertado, elabora um plano para se infiltrar na casa da rica família Park. Uma escalada de eventos inesperados mostra que as diferenças sociais têm consequências devastadoras.",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    video: "https://www.youtube.com/embed/5xH0HfJHsaY?autoplay=1"
  },
  {
    id: 8,
    title: "Vingadores: Ultimato",
    year: 2019,
    duration: "3h 01m",
    rating: 8.4,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ação", "Aventura", "Ficção Científica"],
    description: "Após os eventos devastadores de Thanos, os Vingadores restantes devem se reunir mais uma vez para desfazer suas ações e restaurar a ordem no universo, custando o que for necessário.",
    poster: "https://image.tmdb.org/t/p/w500/q6725aR8Zs4IwGMXzZT2CBlKAU.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    video: "https://www.youtube.com/embed/TcMBFSGVi1c?autoplay=1"
  },
  {
    id: 9,
    title: "Duna",
    year: 2021,
    duration: "2h 35m",
    rating: 8.0,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Aventura", "Drama"],
    description: "Paul Atreides, um jovem brilhante e talentoso, nascido para um grande destino, viaja ao planeta mais perigoso do universo para garantir o futuro de sua família e de seu povo.",
    poster: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
    video: "https://www.youtube.com/embed/n9xhJrPXop4?autoplay=1"
  },
  {
    id: 10,
    title: "Oppenheimer",
    year: 2023,
    duration: "3h 00m",
    rating: 8.4,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Drama", "História"],
    description: "A história do físico J. Robert Oppenheimer e o seu papel no desenvolvimento da bomba atômica durante a Segunda Guerra Mundial, além das consequências morais devastadoras dessa criação.",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
    video: "https://www.youtube.com/embed/uYPbbksJxIg?autoplay=1"
  },
  {
    id: 11,
    title: "Stranger Things",
    year: 2016,
    duration: "4 Temporadas",
    rating: 8.7,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Terror", "Drama"],
    description: "Quando um garoto desaparece misteriosamente, seus amigos, sua mãe e o xerife da cidade investigam o caso, descobrindo experiências secretas do governo, forças sobrenaturais e uma garota estranha.",
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlYj7y8VJOzXkTGg3Zfak.jpg",
    video: "https://www.youtube.com/embed/b9EkMc79ZSU?autoplay=1"
  },
  {
    id: 12,
    title: "Breaking Bad",
    year: 2008,
    duration: "5 Temporadas",
    rating: 9.5,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Crime", "Drama", "Thriller"],
    description: "Walter White, um professor de química do ensino médio que descobre ter câncer terminal, decide começar a produzir metanfetamina com um ex-aluno para garantir o futuro financeiro de sua família.",
    poster: "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW73GM6EQ3GP.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/gc8PfyTqzqltKMCr3gLEoNIt7CB.jpg",
    video: "https://www.youtube.com/embed/HhesaQXLuRY?autoplay=1"
  },
  {
    id: 13,
    title: "The Witcher",
    year: 2019,
    duration: "3 Temporadas",
    rating: 8.2,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Fantasia", "Ação", "Aventura"],
    description: "Geralt de Rívia, um caçador de monstros mutante, luta para encontrar seu lugar em um mundo onde as pessoas muitas vezes se mostram mais perversas do que os monstros que ele enfrenta.",
    poster: "https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/jBJWaqoSCiARWtfV0GlqHrcdiJq.jpg",
    video: "https://www.youtube.com/embed/ndl1W4ltcmg?autoplay=1"
  },
  {
    id: 14,
    title: "Peaky Blinders",
    year: 2013,
    duration: "6 Temporadas",
    rating: 8.8,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Crime", "Drama"],
    description: "Na Birmingham pós-Primeira Guerra, Tommy Shelby lidera os Peaky Blinders, uma das gangues mais temidas da Inglaterra, enquanto tenta expandir seu império e manter a família unida.",
    poster: "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
    video: "https://www.youtube.com/embed/oVzVdvGIC7U?autoplay=1"
  },
  {
    id: 15,
    title: "John Wick 4: Baba Yaga",
    year: 2023,
    duration: "2h 49m",
    rating: 7.7,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ação", "Thriller", "Crime"],
    description: "John Wick enfrenta seu adversário mais letal até agora. Com o preço por sua cabeça cada vez mais alto, ele busca aliados e enfrenta a Alta Mesa em batalhas épicas ao redor do mundo.",
    poster: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7LsyBGSNiVJt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
    video: "https://www.youtube.com/embed/qEVUtrk8_B4?autoplay=1"
  },
  {
    id: 16,
    title: "Blade Runner 2049",
    year: 2017,
    duration: "2h 44m",
    rating: 8.0,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Drama", "Thriller"],
    description: "O oficial K da LAPD descobre um segredo enterrado que pode mergulhar o que resta da sociedade no caos. Sua descoberta o leva a encontrar Rick Deckard, um ex-blade runner desaparecido há 30 anos.",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg",
    video: "https://www.youtube.com/embed/gCcx85zbxz4?autoplay=1"
  },
  {
    id: 17,
    title: "A Casa do Dragão",
    year: 2022,
    duration: "2 Temporadas",
    rating: 8.4,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Fantasia", "Drama", "Ação"],
    description: "Ambientada 200 anos antes dos eventos de Game of Thrones, a série conta a história da Casa Targaryen e da guerra civil que ficou conhecida como a Dança dos Dragões.",
    poster: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    video: "https://www.youtube.com/embed/DotnJ7tTA34?autoplay=1"
  },
  {
    id: 18,
    title: "Gladiador II",
    year: 2024,
    duration: "2h 28m",
    rating: 7.0,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ação", "Aventura", "Drama"],
    description: "Lucius, o filho de Lucilla, é forçado a entrar no Coliseu depois que seu lar é conquistado. Com fúria em seu coração, ele deve lutar pelo futuro de Roma enfrentando tiranos e imperadores corruptos.",
    poster: "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
    video: "https://www.youtube.com/embed/4rgYUipGJNo?autoplay=1"
  },
  {
    id: 128456,
    title: "Elize: Sombras de uma Mulher",
    year: 2021,
    duration: "1h 55m",
    rating: 8.2,
    type: "movie",
    featured: true,
    videoType: "url",
    genres: ["Documentário", "Crime", "Drama"],
    description: "O documentário revela os bastidores, segredos e desdobramentos do crime que chocaria o Brasil, trazendo uma perspectiva profunda sobre o caso de Elize Matsunaga.",
    poster: "https://image.tmdb.org/t/p/w500/vLg51aN7ZndG4i7mR7i1t5e2n0i.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/j9X2o7mR7i1t5e2n0ivLg51aN7Z.jpg",
    video: "https://myembed.biz/filme/128456"
  },
  {
    id: 5920,
    title: "O Mentalista",
    year: 2008,
    duration: "7 Temporadas",
    rating: 8.4,
    type: "series",
    featured: true,
    videoType: "url",
    genres: ["Crime", "Drama", "Mistério"],
    description: "Patrick Jane é um consultor independente da Bureau de Investigação da Califórnia (CBI) que tem um histórico notável de solução de crimes graves usando suas habilidades apuradas de observação e dedução.",
    poster: "https://image.tmdb.org/t/p/w500/ac9nL3r7sB1vW3k0v5X.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/w5Xv3k0v5Xac9nL3r7sB1.jpg",
    video: "https://myembed.biz/serie/5920/1/1"
  }
];

// Gêneros disponíveis
const ALL_GENRES = [
  "Ação", "Aventura", "Comédia", "Crime", "Drama",
  "Fantasia", "Ficção Científica", "História", "Terror", "Thriller"
];

// Catalog of Books, Comics (HQs), and Manga
const DEFAULT_BOOKS = [
  {
    id: "hq-deadpool-01",
    title: "Deadpool Mata Deadpool — Edição 01",
    author: "Marvel Comics",
    year: 2024,
    duration: "HQ Completa (PDF)",
    rating: 9.8,
    type: "book",
    featured: true,
    genres: ["HQs & Quadrinhos", "Ação", "Fantasia & Ficção"],
    description: "Edição 01 da minissérie completa da Marvel em formato PDF. O Mercenário Tagarela inicia sua jornada insana contra versões alternativas de si mesmo pelo multiverso.",
    poster: "assets/hqs/deadpool_01.png",
    backdrop: "assets/hqs/deadpool_01.png",
    readerUrl: "https://drive.google.com/file/d/12t2pkBnPC1wCBQdNJbedEUaiKodtxxel/view?usp=sharing"
  },
  {
    id: "hq-deadpool-02",
    title: "Deadpool Mata Deadpool — Edição 02",
    author: "Marvel Comics",
    year: 2024,
    duration: "HQ Completa (PDF)",
    rating: 9.8,
    type: "book",
    featured: true,
    genres: ["HQs & Quadrinhos", "Ação", "Fantasia & Ficção"],
    description: "Edição 02 da minissérie completa da Marvel em formato PDF. A guerra multiversal dos Deadpools esquenta com batalhas épicas e insanas.",
    poster: "assets/hqs/deadpool_02.png",
    backdrop: "assets/hqs/deadpool_02.png",
    readerUrl: "https://drive.google.com/file/d/1-H1XE4ulEDBgBN81_SkS3v3MtcWPeJfx/view?usp=sharing"
  },
  {
    id: "hq-deadpool-03",
    title: "Deadpool Mata Deadpool — Edição 03",
    author: "Marvel Comics",
    year: 2024,
    duration: "HQ Completa (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["HQs & Quadrinhos", "Ação", "Fantasia & Ficção"],
    description: "Edição 03 da minissérie completa da Marvel em formato PDF. Os sobreviventes se preparam para a grande batalha final pelo destino da realidade.",
    poster: "assets/hqs/deadpool_03.png",
    backdrop: "assets/hqs/deadpool_03.png",
    readerUrl: "https://drive.google.com/file/d/15byeGXNz5Sf1KxViotdY92kHBbr_zf_v/view?usp=sharing"
  },
  {
    id: "hq-deadpool-04",
    title: "Deadpool Mata Deadpool — Edição 04",
    author: "Marvel Comics",
    year: 2024,
    duration: "HQ Completa (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["HQs & Quadrinhos", "Ação", "Fantasia & Ficção"],
    description: "Edição 04 (Final) da minissérie completa da Marvel em formato PDF. O confronto definitivo que encerrará a caçada do Mercenário Tagarela.",
    poster: "https://i.imgur.com/cb5ZH4n.png",
    backdrop: "https://i.imgur.com/cb5ZH4n.png",
    readerUrl: "https://drive.google.com/file/d/1aSmhGLnvlIykGnSgx8tJ4-u0BZYN1KjW/view?usp=sharing"
  },
  {
    id: "livro-simplesmente-acontece",
    title: "Simplesmente Acontece",
    author: "Cecelia Ahern",
    year: 2014,
    duration: "Livro Completo (PDF)",
    rating: 9.8,
    type: "book",
    featured: true,
    genres: ["Romance & Drama", "Fantasia & Ficção", "Clássicos"],
    description: "Alex e Rosie são amigos inseparáveis que cresceram juntos em Dublin. Uma história apaixonante e emocionante sobre o amor, o tempo e os caminhos da vida. Clique para ler o livro completo!",
    poster: "https://br.web.img3.acsta.net/pictures/14/12/11/15/29/051042.jpg",
    backdrop: "https://br.web.img3.acsta.net/pictures/14/12/11/15/29/051042.jpg",
    readerUrl: "https://drive.google.com/file/d/10a3h7LWXg2R-HWgRI8-_doCyIaS2TnI4/view?usp=sharing"
  },
  {
    id: "livro-do-bill",
    title: "O Livro do Bill",
    author: "Alex Hirsch (Gravity Falls)",
    year: 2024,
    duration: "Livro Completo (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["Terror & Mistério", "Fantasia & Ficção", "Desenvolvimento & Educação"],
    description: "Escrito pelo mestre da bizarrice Bill Cipher em pessoa! Explore as origens mais obscuras e sinistras do universo de Gravity Falls nesta obra inigualável. Clique para ler o livro completo!",
    poster: "https://m.media-amazon.com/images/I/81IioFHXeOL._UF1000,1000_QL80_.jpg",
    backdrop: "https://m.media-amazon.com/images/I/81IioFHXeOL._UF1000,1000_QL80_.jpg",
    readerUrl: "https://drive.google.com/file/d/1WnNN-a8RSWJ03om36v6oLr0YD-_B3m8n/view?usp=sharing"
  },
  {
    id: "livro-warren-lugar-sombrio",
    title: "Ed & Lorraine Warren: Lugar Sombrio",
    author: "Ed & Lorraine Warren",
    year: 2019,
    duration: "Livro Completo (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["Terror & Mistério", "Fantasia & Ficção", "Clássicos"],
    description: "Os demonologistas mais famosos do mundo investigam casos aterrorizantes e sobrenaturais de casas assombradas e espíritos demoníacos. Clique para ler o livro completo!",
    poster: "https://m.media-amazon.com/images/I/A1Cb9Ffck8L._UF1000,1000_QL80_.jpg",
    backdrop: "https://m.media-amazon.com/images/I/A1Cb9Ffck8L._UF1000,1000_QL80_.jpg",
    readerUrl: "https://drive.google.com/file/d/1aMDH7Tc8hFaylJZ-68af8oTiW22BG7Du/view?usp=sharing"
  },
  {
    id: "livro-warren-demonologistas",
    title: "Ed & Lorraine Warren: Demonologistas",
    author: "Ed & Lorraine Warren / Gerald Brittle",
    year: 2016,
    duration: "Livro Completo (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["Terror & Mistério", "Fantasia & Ficção", "Clássicos"],
    description: "A biografia definitiva dos demonologistas mais famosos do mundo. Casos reais assustadores, arquivos sobrenaturais e investigações paranormais detalhadas. Clique para ler o livro completo!",
    poster: "https://images.tcdn.com.br/img/img_prod/1175968/ed_amp_lorraine_warrer_demonologistas_arquivos_sobrenaturais_55071_1_d36a7e44ad47462868012bb0ca74d0c9.jpg",
    backdrop: "https://images.tcdn.com.br/img/img_prod/1175968/ed_amp_lorraine_warrer_demonologistas_arquivos_sobrenaturais_55071_1_d36a7e44ad47462868012bb0ca74d0c9.jpg",
    readerUrl: "https://drive.google.com/file/d/1-5e07Jt30ajZqKXrZbKsC6plPLMoEqFd/view?usp=sharing"
  },
  {
    id: "livro-warren-vidas-eternas",
    title: "Ed & Lorraine Warren: Vidas Eternas",
    author: "Ed & Lorraine Warren",
    year: 2019,
    duration: "Livro Completo (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["Terror & Mistério", "Fantasia & Ficção", "Clássicos"],
    description: "Casos reais impressionantes de reencarnação, vidas passadas e mistérios espirituais investigados pelos maiores especialistas do sobrenatural. Clique para ler o livro completo!",
    poster: "https://m.media-amazon.com/images/I/A1E6cdLODLL._UF1000,1000_QL80_.jpg",
    backdrop: "https://m.media-amazon.com/images/I/A1E6cdLODLL._UF1000,1000_QL80_.jpg",
    readerUrl: "https://drive.google.com/file/d/1GP-S7PbzgMU8WYda5S1dx0g8rIgPBRlQ/view?usp=sharing"
  },
  {
    id: "livro-culpa-e-das-estrelas",
    title: "A Culpa É das Estrelas",
    author: "John Green",
    year: 2012,
    duration: "Livro Completo (PDF)",
    rating: 9.8,
    type: "book",
    featured: true,
    genres: ["Romance & Drama", "Clássicos", "Desenvolvimento & Educação"],
    description: "Hazel e Augustus são dois adolescentes que se conhecem em um grupo de apoio a pacientes com câncer e vivem uma linda e emocionante história de amor inesquecível. Clique para ler o livro completo!",
    poster: "https://m.media-amazon.com/images/I/51UgEgRAf4L._SY445_SX342_ML2_.jpg",
    backdrop: "https://m.media-amazon.com/images/I/51UgEgRAf4L._SY445_SX342_ML2_.jpg",
    readerUrl: "https://drive.google.com/file/d/14F06E9QQWGt1-jlJFJyz1WwmxZwoezW3/view?usp=sharing"
  },
  {
    id: "livro-exorcismo",
    title: "Exorcismo",
    author: "Thomas B. Allen",
    year: 2014,
    duration: "Livro Completo (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["Terror & Mistério", "Fantasia & Ficção", "Clássicos"],
    description: "A história real que inspirou o maior filme de terror de todos os tempos. O diário verdadeiro do padre e a terrível possessão de Robbie Mannheim em 1949. Clique para ler o livro completo!",
    poster: "https://darkside.vtexassets.com/arquivos/ids/167914/64-exorcismo-thomas-b-allen-0.jpg?v=636802539595270000",
    backdrop: "https://darkside.vtexassets.com/arquivos/ids/167914/64-exorcismo-thomas-b-allen-0.jpg?v=636802539595270000",
    readerUrl: "https://drive.google.com/file/d/1S5KkXg7PYrnnPzCQvhFhFmDLpn6k1FiC/view?usp=sharing"
  },
  {
    id: "livro-homem-de-giz",
    title: "O Homem de Giz",
    author: "C.J. Tudor",
    year: 2018,
    duration: "Livro Completo (PDF)",
    rating: 9.8,
    type: "book",
    featured: true,
    genres: ["Terror & Mistério", "Fantasia & Ficção", "Clássicos"],
    description: "Um grupo de crianças usava bonecos de giz para mandar mensagens secretas. Trinta anos depois, o passado sombrio e os segredos mortais voltam para assombrá-los. Clique para ler o livro completo!",
    poster: "https://static.estantevirtual.com.br/book/00/COJ-2794-000/COJ-2794-000_detail1.jpg?ts=1720029764445&ims=fit-in/600x800/filters:fill(fff):quality(100)",
    backdrop: "https://static.estantevirtual.com.br/book/00/COJ-2794-000/COJ-2794-000_detail1.jpg?ts=1720029764445&ims=fit-in/600x800/filters:fill(fff):quality(100)",
    readerUrl: "https://drive.google.com/file/d/17R4EHSOgAJMp43WRwP2l8iX6rxhcjlSn/view?usp=sharing"
  },
  {
    id: "livro-interestelar",
    title: "Interestelar",
    author: "Kip Thorne & Greg Keyes",
    year: 2014,
    duration: "Livro Completo (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["Fantasia & Ficção", "Desenvolvimento & Educação", "Clássicos"],
    description: "As reservas da Terra estão no fim. Uma expedição espacial atravessa um buraco de minhoca no espaço-tempo em busca de um novo lar para a humanidade. A ciência e ficção por trás da obra-prima. Clique para ler o livro completo!",
    poster: "https://i.pinimg.com/564x/0d/4f/bd/0d4fbdfdb1ed726b86f6127aa9a4850f.jpg",
    backdrop: "https://i.pinimg.com/564x/0d/4f/bd/0d4fbdfdb1ed726b86f6127aa9a4850f.jpg",
    readerUrl: "https://drive.google.com/file/d/1yYUAMTR_7Ig2MeExC8EpSChQAO8RG7Fr/view?usp=sharing"
  },
  {
    id: "livro-o-exorcista",
    title: "O Exorcista",
    author: "William Peter Blatty",
    year: 1971,
    duration: "Livro Completo (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["Terror & Mistério", "Fantasia & Ficção", "Clássicos"],
    description: "Um dos maiores clássicos do terror de todos os tempos. A aterrorizante história da garota Regan MacNeil, tomada por uma força demoníaca sombria. Clique para ler o livro completo!",
    poster: "https://m.media-amazon.com/images/I/91fQ51I4TRL.jpg",
    backdrop: "https://m.media-amazon.com/images/I/91fQ51I4TRL.jpg",
    readerUrl: "https://drive.google.com/file/d/1QpTroiYBeuA46VzXgDF_NRrYCI8ypyzT/view?usp=sharing"
  },
  {
    id: "livro-bussola-de-ouro",
    title: "A Bússola de Ouro",
    author: "Philip Pullman",
    year: 1995,
    duration: "Livro Completo (PDF)",
    rating: 9.8,
    type: "book",
    featured: true,
    genres: ["Fantasia & Ficção", "Desenvolvimento & Educação", "Clássicos"],
    description: "Lyra Belacqua vive em um mundo onde cada ser humano é acompanhado por um daimon. Ao investigar o sequestro de crianças, ela descobre segredos sombrios e um instrumento poderoso: o aletiômetro. Clique para ler!",
    poster: "https://m.media-amazon.com/images/I/91T-vC38laL._AC_UF1000,1000_QL80_AIweblab1381794,T1_.jpg",
    backdrop: "https://m.media-amazon.com/images/I/91T-vC38laL._AC_UF1000,1000_QL80_AIweblab1381794,T1_.jpg",
    readerUrl: "https://drive.google.com/file/d/1DtmJS3bg_zumqdku5m3ttMcQU-S0kNJM/view?usp=sharing"
  },
  {
    id: "livro-harry-potter-reliquias-da-morte",
    title: "Harry Potter e as Relíquias da Morte",
    author: "J.K. Rowling",
    year: 2007,
    duration: "Livro Completo (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["Fantasia & Ficção", "Clássicos", "Desenvolvimento & Educação"],
    description: "O capítulo final e épico da saga do menino bruxo. Harry, Rony e Hermione saem em uma perigosa missão para destruir as Horcruxes e enfrentar Lord Voldemort na Batalha de Hogwarts. Clique para ler!",
    poster: "https://rocco.com.br/wp-content/uploads/2024/04/9786555324075.jpg",
    backdrop: "https://rocco.com.br/wp-content/uploads/2024/04/9786555324075.jpg",
    readerUrl: "https://drive.google.com/file/d/1OZlZPnctuB9m7tPhdWIGS3t7Z7dilclh/view?usp=sharing"
  },
  {
    id: "livro-atraves-da-minha-janela",
    title: "Através da Minha Janela",
    author: "Ariana Godoy",
    year: 2019,
    duration: "Livro Completo (PDF)",
    rating: 9.8,
    type: "book",
    featured: true,
    genres: ["Romance & Drama", "Clássicos", "Desenvolvimento & Educação"],
    description: "Raquel é apaixonada por Ares, seu vizinho atraente e misterioso. Ela o observa em segredo através da janela, até que uma senha de Wi-Fi compartilhada desencadeia um jogo de sedução e um romance intenso. Clique para ler!",
    poster: "https://i.pinimg.com/originals/4b/4b/6a/4b4b6aa34905d24957b061b97fdb4a8e.jpg",
    backdrop: "https://i.pinimg.com/originals/4b/4b/6a/4b4b6aa34905d24957b061b97fdb4a8e.jpg",
    readerUrl: "https://drive.google.com/file/d/146Yzl4Bkmif-xX7PCr2v-9HFoyuYl5FJ/view?usp=sharing"
  },
  {
    id: "livro-diarios-do-vampiro-destino",
    title: "Diários do Vampiro: O Destino",
    author: "L.J. Smith",
    year: 2012,
    duration: "Livro Completo (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["Terror & Mistério", "Fantasia & Ficção", "Romance & Drama"],
    description: "Elena Gilbert enfrenta seu destino supremo. Em meio ao triângulo amoroso épico com os irmãos vampiros Stefan e Damon Salvatore, forças das trevas ameaçam destruir Fell's Church para sempre. Clique para ler!",
    poster: "https://m.media-amazon.com/images/I/612NcXJzsdL.jpg",
    backdrop: "https://m.media-amazon.com/images/I/612NcXJzsdL.jpg",
    readerUrl: "https://drive.google.com/file/d/1ILpQcnLmXltTli04WamXSB-f54Tt98QE/view?usp=sharing"
  },
  {
    id: "hq-invencivel-vol-01",
    title: "Invencível — Volume 1",
    author: "Robert Kirkman (Image Comics)",
    year: 2003,
    duration: "HQ Completa (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["HQs & Quadrinhos", "Ação", "Fantasia & Ficção"],
    description: "Mark Grayson é um garoto comum do ensino médio, exceto pelo fato de seu pai ser o Omni-Man, o super-herói mais poderoso do planeta. Quando Mark desenvolve seus próprios poderes, sua vida muda para sempre. Clique para ler!",
    poster: "https://imagecomics.com/files/releases/Invincible_01-1.jpg",
    backdrop: "https://imagecomics.com/files/releases/Invincible_01-1.jpg",
    readerUrl: "https://drive.google.com/file/d/1T1WadPk6yXF9FKaV5rYzuBr_HNT9WS0N/view?usp=sharing"
  },
  {
    id: "hq-invencivel-vol-02",
    title: "Invencível — Volume 2",
    author: "Robert Kirkman (Image Comics)",
    year: 2004,
    duration: "HQ Completa (PDF)",
    rating: 9.9,
    type: "book",
    featured: true,
    genres: ["HQs & Quadrinhos", "Ação", "Fantasia & Ficção"],
    description: "As consequências devastadoras da revelação sobre Omni-Man deixam Mark Grayson e o mundo abalados. Mark precisa assumir o manto de defensor da Terra e enfrentar novas ameaças galácticas. Clique para ler!",
    poster: "https://m.media-amazon.com/images/I/618mNqdHzCL._UF1000,1000_QL80_.jpg",
    backdrop: "https://m.media-amazon.com/images/I/618mNqdHzCL._UF1000,1000_QL80_.jpg",
    readerUrl: "https://drive.google.com/file/d/1ZIiGfcm5HwRsdJ7mqyhwyGv721V3QGMa/view?usp=sharing"
  }
];

const BOOK_GENRES = [
  "Todos",
  "HQs & Quadrinhos",
  "Romance & Drama",
  "Fantasia & Ficção",
  "Terror & Mistério",
  "Desenvolvimento & Educação",
  "Clássicos"
];
