// ============================================================
// DarkFlix - Dados Iniciais de Filmes e Séries
// ============================================================

const DEFAULT_MOVIES = [
  {
    id: 1,
    title: "Interestelar",
    year: 2014,
    duration: "2h 49m",
    rating: 8.7,
    type: "movie",
    featured: true,
    videoType: "url",
    genres: ["Ficção Científica", "Drama", "Aventura"],
    description: "As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, garantindo a sobrevivência da espécie humana.",
    poster: "https://image.tmdb.org/t/p/w500/nCbkOyOMTEwlEV0LtCObySSRFhk.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg",
    video: "https://www.youtube.com/embed/zSWdZVtXT7E?autoplay=1"
  },
  {
    id: 2,
    title: "O Poderoso Chefão",
    year: 1972,
    duration: "2h 55m",
    rating: 9.2,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Crime", "Drama"],
    description: "Uma família de Nova York, durante os anos 40, é chefiada por Don Vito Corleone. Ele é o chefão da máfia e comanda com mão de ferro os negócios ilícitos, se tornando o homem mais poderoso da cidade.",
    poster: "https://image.tmdb.org/t/p/w500/oJagOzBu9Rdd9BrciseCm3U3MCU.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    video: "https://www.youtube.com/embed/UaVTIH8mujA?autoplay=1"
  },
  {
    id: 3,
    title: "Batman: O Cavaleiro das Trevas",
    year: 2008,
    duration: "2h 32m",
    rating: 9.0,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ação", "Crime", "Drama"],
    description: "Com a ajuda do tenente Jim Gordon e do promotor público Harvey Dent, Batman enfrenta o Coringa, um gênio do crime que semeia o caos e a destruição em Gotham City.",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BytUESw3KFkt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg",
    video: "https://www.youtube.com/embed/EXeTwQWrcwY?autoplay=1"
  },
  {
    id: 4,
    title: "Clube da Luta",
    year: 1999,
    duration: "2h 19m",
    rating: 8.8,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Drama", "Thriller"],
    description: "Um homem deprimido que sofre de insônia conhece Tyler Durden, um vendedor de sabão despreocupado. Juntos, eles formam um clube do luta clandestino que evolui para algo muito mais perigoso.",
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/hZkgoQYus5dXo3H8T7CYV2UImTl.jpg",
    video: "https://www.youtube.com/embed/qtRKdVHc-cE?autoplay=1"
  },
  {
    id: 5,
    title: "Inception: A Origem",
    year: 2010,
    duration: "2h 28m",
    rating: 8.8,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Ação", "Thriller"],
    description: "Dom Cobb é um ladrão habilidoso que rouba segredos corporativos usando tecnologia de compartilhamento de sonhos. Ele recebe a chance de ter sua vida de volta se conseguir realizar o inverso: implantar uma ideia na mente de alguém.",
    poster: "https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    video: "https://www.youtube.com/embed/YoHD9XEInc0?autoplay=1"
  },
  {
    id: 6,
    title: "Matrix",
    year: 1999,
    duration: "2h 16m",
    rating: 8.7,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Ação"],
    description: "O hacker Neo descobre que o mundo em que vive é uma realidade simulada criada por máquinas. Guiado por Morpheus, ele embarca em uma jornada para libertar a humanidade.",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
    video: "https://www.youtube.com/embed/vKQi3bBA1y8?autoplay=1"
  },
  {
    id: 7,
    title: "Parasita",
    year: 2019,
    duration: "2h 12m",
    rating: 8.5,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Thriller", "Comédia", "Drama"],
    description: "A família Kim, que vive em um porão apertado, elabora um plano para se infiltrar na casa da rica família Park. Uma escalada de eventos inesperados mostra que as diferenças sociais têm consequências devastadoras.",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    video: "https://www.youtube.com/embed/5xH0HfJHsaY?autoplay=1"
  },
  {
    id: 8,
    title: "Vingadores: Ultimato",
    year: 2019,
    duration: "3h 01m",
    rating: 8.4,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ação", "Aventura", "Ficção Científica"],
    description: "Após os eventos devastadores de Thanos, os Vingadores restantes devem se reunir mais uma vez para desfazer suas ações e restaurar a ordem no universo, custando o que for necessário.",
    poster: "https://image.tmdb.org/t/p/w500/q6725aR8Zs4IwGMXzZT2CBlKAU.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    video: "https://www.youtube.com/embed/TcMBFSGVi1c?autoplay=1"
  },
  {
    id: 9,
    title: "Duna",
    year: 2021,
    duration: "2h 35m",
    rating: 8.0,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Aventura", "Drama"],
    description: "Paul Atreides, um jovem brilhante e talentoso, nascido para um grande destino, viaja ao planeta mais perigoso do universo para garantir o futuro de sua família e de seu povo.",
    poster: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
    video: "https://www.youtube.com/embed/n9xhJrPXop4?autoplay=1"
  },
  {
    id: 10,
    title: "Oppenheimer",
    year: 2023,
    duration: "3h 00m",
    rating: 8.4,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Drama", "História"],
    description: "A história do físico J. Robert Oppenheimer e o seu papel no desenvolvimento da bomba atômica durante a Segunda Guerra Mundial, além das consequências morais devastadoras dessa criação.",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
    video: "https://www.youtube.com/embed/uYPbbksJxIg?autoplay=1"
  },
  {
    id: 11,
    title: "Stranger Things",
    year: 2016,
    duration: "4 Temporadas",
    rating: 8.7,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Terror", "Drama"],
    description: "Quando um garoto desaparece misteriosamente, seus amigos, sua mãe e o xerife da cidade investigam o caso, descobrindo experiências secretas do governo, forças sobrenaturais e uma garota estranha.",
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlYj7y8VJOzXkTGg3Zfak.jpg",
    video: "https://www.youtube.com/embed/b9EkMc79ZSU?autoplay=1"
  },
  {
    id: 12,
    title: "Breaking Bad",
    year: 2008,
    duration: "5 Temporadas",
    rating: 9.5,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Crime", "Drama", "Thriller"],
    description: "Walter White, um professor de química do ensino médio que descobre ter câncer terminal, decide começar a produzir metanfetamina com um ex-aluno para garantir o futuro financeiro de sua família.",
    poster: "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW73GM6EQ3GP.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/gc8PfyTqzqltKMCr3gLEoNIt7CB.jpg",
    video: "https://www.youtube.com/embed/HhesaQXLuRY?autoplay=1"
  },
  {
    id: 13,
    title: "The Witcher",
    year: 2019,
    duration: "3 Temporadas",
    rating: 8.2,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Fantasia", "Ação", "Aventura"],
    description: "Geralt de Rívia, um caçador de monstros mutante, luta para encontrar seu lugar em um mundo onde as pessoas muitas vezes se mostram mais perversas do que os monstros que ele enfrenta.",
    poster: "https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/jBJWaqoSCiARWtfV0GlqHrcdiJq.jpg",
    video: "https://www.youtube.com/embed/ndl1W4ltcmg?autoplay=1"
  },
  {
    id: 14,
    title: "Peaky Blinders",
    year: 2013,
    duration: "6 Temporadas",
    rating: 8.8,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Crime", "Drama"],
    description: "Na Birmingham pós-Primeira Guerra, Tommy Shelby lidera os Peaky Blinders, uma das gangues mais temidas da Inglaterra, enquanto tenta expandir seu império e manter a família unida.",
    poster: "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
    video: "https://www.youtube.com/embed/oVzVdvGIC7U?autoplay=1"
  },
  {
    id: 15,
    title: "John Wick 4: Baba Yaga",
    year: 2023,
    duration: "2h 49m",
    rating: 7.7,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ação", "Thriller", "Crime"],
    description: "John Wick enfrenta seu adversário mais letal até agora. Com o preço por sua cabeça cada vez mais alto, ele busca aliados e enfrenta a Alta Mesa em batalhas épicas ao redor do mundo.",
    poster: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7LsyBGSNiVJt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
    video: "https://www.youtube.com/embed/qEVUtrk8_B4?autoplay=1"
  },
  {
    id: 16,
    title: "Blade Runner 2049",
    year: 2017,
    duration: "2h 44m",
    rating: 8.0,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Drama", "Thriller"],
    description: "O oficial K da LAPD descobre um segredo enterrado que pode mergulhar o que resta da sociedade no caos. Sua descoberta o leva a encontrar Rick Deckard, um ex-blade runner desaparecido há 30 anos.",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg",
    video: "https://www.youtube.com/embed/gCcx85zbxz4?autoplay=1"
  },
  {
    id: 17,
    title: "A Casa do Dragão",
    year: 2022,
    duration: "2 Temporadas",
    rating: 8.4,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Fantasia", "Drama", "Ação"],
    description: "Ambientada 200 anos antes dos eventos de Game of Thrones, a série conta a história da Casa Targaryen e da guerra civil que ficou conhecida como a Dança dos Dragões.",
    poster: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    video: "https://www.youtube.com/embed/DotnJ7tTA34?autoplay=1"
  },
  {
    id: 18,
    title: "Gladiador II",
    year: 2024,
    duration: "2h 28m",
    rating: 7.0,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ação", "Aventura", "Drama"],
    description: "Lucius, o filho de Lucilla, é forçado a entrar no Coliseu depois que seu lar é conquistado. Com fúria em seu coração, ele deve lutar pelo futuro de Roma enfrentando tiranos e imperadores corruptos.",
    poster: "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
    video: "https://www.youtube.com/embed/4rgYUipGJNo?autoplay=1"
  },
  {
    id: 128456,
    title: "Elize: Sombras de uma Mulher",
    year: 2021,
    duration: "1h 55m",
    rating: 8.2,
    type: "movie",
    featured: true,
    videoType: "url",
    genres: ["Documentário", "Crime", "Drama"],
    description: "O documentário revela os bastidores, segredos e desdobramentos do crime que chocaria o Brasil, trazendo uma perspectiva profunda sobre o caso de Elize Matsunaga.",
    poster: "https://image.tmdb.org/t/p/w500/vLg51aN7ZndG4i7mR7i1t5e2n0i.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/j9X2o7mR7i1t5e2n0ivLg51aN7Z.jpg",
    video: "https://myembed.biz/filme/128456"
  },
  {
    id: 5920,
    title: "O Mentalista",
    year: 2008,
    duration: "7 Temporadas",
    rating: 8.4,
    type: "series",
    featured: true,
    videoType: "url",
    genres: ["Crime", "Drama", "Mistério"],
    description: "Patrick Jane é um consultor independente da Bureau de Investigação da Califórnia (CBI) que tem um histórico notável de solução de crimes graves usando suas habilidades apuradas de observação e dedução.",
    poster: "https://image.tmdb.org/t/p/w500/ac9nL3r7sB1vW3k0v5X.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/w5Xv3k0v5Xac9nL3r7sB1.jpg",
    video: "https://myembed.biz/serie/5920/1/1"
  }
];

// Gêneros disponíveis
const ALL_GENRES = [
  "Ação", "Aventura", "Comédia", "Crime", "Drama",
  "Fantasia", "Ficção Científica", "História", "Terror", "Thriller"
];

// Catalog of Books, Comics (HQs), and Manga
const DEFAULT_BOOKS = [
  {
    id: "book-1",
    title: "O Pequeno Príncipe",
    author: "Antoine de Saint-Exupéry",
    year: 1943,
    duration: "96 Páginas",
    rating: 9.8,
    type: "book",
    featured: true,
    genres: ["Fantasia & Ficção", "Clássicos"],
    description: "Um piloto cai no deserto do Saara e encontra um jovem príncipe que viajou de seu pequeno asteroide. Uma fábula poética sobre amizade, amor e o sentido da vida.",
    poster: "https://m.media-amazon.com/images/I/71O2XIytdEL._AC_UF1000,1000_QL80_.jpg",
    backdrop: "https://m.media-amazon.com/images/S/pv-target-images/0e1d8a39b33a5980a312275210c4f8263152d5b62b10a9bd4d32a92631165a28._SX1080_.jpg",
    readerUrl: "https://drive.google.com/file/d/1aSmhGLnvlIykGnSgx8tJ4-u0BZYN1KjW/view?usp=sharing"
  },
  {
    id: "book-2",
    title: "Homem-Aranha: A Última Caçada de Kraven",
    author: "J.M. DeMatteis / Marvel Comics",
    year: 1987,
    duration: "144 Páginas",
    rating: 9.6,
    type: "book",
    featured: true,
    genres: ["HQs & Quadrinhos", "Ação"],
    description: "Kraven, o Caçador, realiza seu derradeiro plano para derrotar o Homem-Aranha e provar sua superioridade, enterrando o herói vivo e assumindo seu manto.",
    poster: "https://m.media-amazon.com/images/I/91r4mH0P37L._AC_UF1000,1000_QL80_.jpg",
    backdrop: "https://static1.cbrimages.com/wordpress/wp-content/uploads/2021/08/Spider-Man-Kravens-Last-Hunt.jpg",
    readerUrl: "https://drive.google.com/file/d/1aSmhGLnvlIykGnSgx8tJ4-u0BZYN1KjW/view?usp=sharing"
  },
  {
    id: "book-3",
    title: "Batman: A Piada Mortal",
    author: "Alan Moore / DC Comics",
    year: 1988,
    duration: "64 Páginas",
    rating: 9.7,
    type: "book",
    featured: false,
    genres: ["HQs & Quadrinhos", "Terror & Mistério"],
    description: "Uma história sombria que explora as origens do Coringa e seu plano maquiavélico para provar que basta um dia ruim para enlouquecer o homem mais são.",
    poster: "https://m.media-amazon.com/images/I/81xZ-l7N77L._AC_UF1000,1000_QL80_.jpg",
    backdrop: "https://m.media-amazon.com/images/S/pv-target-images/3f283c482ed31e67041f02170363297a731b790d9a74a106e2311894d03998f8._SX1080_.jpg",
    readerUrl: "https://drive.google.com/file/d/1aSmhGLnvlIykGnSgx8tJ4-u0BZYN1KjW/view?usp=sharing"
  },
  {
    id: "book-4",
    title: "O Hobbit",
    author: "J.R.R. Tolkien",
    year: 1937,
    duration: "310 Páginas",
    rating: 9.5,
    type: "book",
    featured: false,
    genres: ["Fantasia & Ficção", "Aventura"],
    description: "Bilbo Bolseiro vivia uma vida calma no Condado até receber a visita do mago Gandalf e treze anões em uma jornada perigosa para recuperar o Reino de Erebor.",
    poster: "https://m.media-amazon.com/images/I/91M9xPfd10L._AC_UF1000,1000_QL80_.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/hZkgoQYus5dXo3H8T7CYV2UImTl.jpg",
    readerUrl: "https://drive.google.com/file/d/1aSmhGLnvlIykGnSgx8tJ4-u0BZYN1KjW/view?usp=sharing"
  },
  {
    id: "book-5",
    title: "Drácula",
    author: "Bram Stoker",
    year: 1897,
    duration: "416 Páginas",
    rating: 9.4,
    type: "book",
    featured: false,
    genres: ["Terror & Mistério", "Clássicos"],
    description: "Jonathan Harker viaja à Transilvânia para fechar um negócio imobiliário com o Conde Drácula e descobre os horrores inomináveis do vampiro milenar.",
    poster: "https://m.media-amazon.com/images/I/81x1R0VqVIL._AC_UF1000,1000_QL80_.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
    readerUrl: "https://drive.google.com/file/d/1aSmhGLnvlIykGnSgx8tJ4-u0BZYN1KjW/view?usp=sharing"
  },
  {
    id: "book-6",
    title: "Pai Rico, Pai Pobre",
    author: "Robert T. Kiyosaki",
    year: 1997,
    duration: "336 Páginas",
    rating: 9.3,
    type: "book",
    featured: false,
    genres: ["Desenvolvimento & Educação"],
    description: "O livro número 1 em finanças pessoais que ensina os conceitos de independência financeira, investimento e gestão patrimonial para mudar a mentalidade sobre dinheiro.",
    poster: "https://m.media-amazon.com/images/I/81bsw6fnUiL._AC_UF1000,1000_QL80_.jpg",
    backdrop: "https://m.media-amazon.com/images/I/81bsw6fnUiL._AC_UF1000,1000_QL80_.jpg",
    readerUrl: "https://drive.google.com/file/d/1aSmhGLnvlIykGnSgx8tJ4-u0BZYN1KjW/view?usp=sharing"
  },
  {
    id: "book-7",
    title: "Attack on Titan — Vol. 01",
    author: "Hajime Isayama",
    year: 2009,
    duration: "192 Páginas",
    rating: 9.6,
    type: "book",
    featured: false,
    genres: ["HQs & Quadrinhos", "Fantasia & Ficção"],
    description: "A humanidade vive cercada por muralhas gigantescas para se proteger de gigantes devoradores chamados Titãs. Eren Yeager jura exterminar todos os Titãs.",
    poster: "https://m.media-amazon.com/images/I/91tK3CWW90L._AC_UF1000,1000_QL80_.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    readerUrl: "https://drive.google.com/file/d/1aSmhGLnvlIykGnSgx8tJ4-u0BZYN1KjW/view?usp=sharing"
  }
];

const BOOK_GENRES = [
  "Todos",
  "HQs & Quadrinhos",
  "Fantasia & Ficção",
  "Terror & Mistério",
  "Desenvolvimento & Educação",
  "Clássicos"
];
